In [36]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier, VotingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, recall_score,classification_report,accuracy_score

In [37]:
msg_dataframe = pd.read_csv(r"C:\Users\pjbah\Downloads\spam.csv")
msg_dataframe.head()

make  address   all   3d   our  over  remove  internet  order  mail  ...  \
0  0.00     0.00  0.29  0.0  0.00  0.00    0.00      0.00   0.00  0.00  ...   
1  0.46     0.00  0.00  0.0  0.00  0.00    0.00      0.00   0.00  0.00  ...   
2  0.00     0.00  0.00  0.0  0.00  0.00    0.00      0.00   0.00  0.00  ...   
3  0.33     0.44  0.37  0.0  0.14  0.11    0.00      0.07   0.97  1.16  ...   
4  0.00     2.08  0.00  0.0  3.12  0.00    1.04      0.00   0.00  0.00  ...   

   semicol  paren  bracket   bang  dollar  pound  cap_avg  cap_long  \
0    0.000  0.178      0.0  0.044   0.000   0.00    1.666        10   
1    0.000  0.125      0.0  0.000   0.000   0.00    1.510        10   
2    0.000  0.000      0.0  0.000   0.000   0.00    1.718        11   
3    0.006  0.159      0.0  0.069   0.221   0.11    3.426        72   
4    0.000  0.000      0.0  0.263   0.000   0.00    1.428         4   

   cap_total  Class  
0        180    ham  
1         74    ham  
2         55    ham  
3        819   spam  
4         20   spam  

[5 rows x 58 columns]

In [3]:
# To check whether there are any null values
msg_dataframe.isna().any().all()

False

In [4]:
msg_dataframe.describe()

make      address          all           3d          our  \
count  4601.000000  4601.000000  4601.000000  4601.000000  4601.000000   
mean      0.104553     0.213015     0.280656     0.065425     0.312223   
std       0.305358     1.290575     0.504143     1.395151     0.672513   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.420000     0.000000     0.380000   
max       4.540000    14.280000     5.100000    42.810000    10.000000   

              over       remove     internet        order         mail  ...  \
count  4601.000000  4601.000000  4601.000000  4601.000000  4601.000000  ...   
mean      0.095901     0.114208     0.105295     0.090067     0.239413  ...   
std       0.273824     0.391441     0.401071     0.278616     0.644755  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     0.000000     0.000000     0.000000     0.160000  ...   
max       5.880000     7.270000    11.110000     5.260000    18.180000  ...   

        conference      semicol        paren      bracket         bang  \
count  4601.000000  4601.000000  4601.000000  4601.000000  4601.000000   
mean      0.031869     0.038575     0.139030     0.016976     0.269071   
std       0.285735     0.243471     0.270355     0.109394     0.815672   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.065000     0.000000     0.000000   
75%       0.000000     0.000000     0.188000     0.000000     0.315000   
max      10.000000     4.385000     9.752000     4.081000    32.478000   

            dollar        pound      cap_avg     cap_long     cap_total  
count  4601.000000  4601.000000  4601.000000  4601.000000   4601.000000  
mean      0.075811     0.044238     5.191515    52.172789    283.289285  
std       0.245882     0.429342    31.729449   194.891310    606.347851  
min       0.000000     0.000000     1.000000     1.000000      1.000000  
25%       0.000000     0.000000     1.588000     6.000000     35.000000  
50%       0.000000     0.000000     2.276000    15.000000     95.000000  
75%       0.052000     0.000000     3.706000    43.000000    266.000000  
max       6.003000    19.829000  1102.500000  9989.000000  15841.000000  

[8 rows x 57 columns]

In [5]:
# Gives the total count of each class variable
spam_ham = msg_dataframe['Class'].value_counts()
spam_ham

ham     2788
spam    1813
Name: Class, dtype: int64

In [38]:
# label encoding the class variables
label_encoder = LabelEncoder()
msg_dataframe['Class']= label_encoder.fit_transform(msg_dataframe['Class'])
# ham 0 spam 1

In [39]:
# Assigning a variable to target variable and feature set
y=msg_dataframe["Class"]
msg_dataframe.drop(['Class'],axis=1,inplace=True)
x=msg_dataframe

In [8]:
# Splitting the train and test data
X_train,X_test,y_train,y_test= train_test_split(x,y, test_size=0.78)

In [9]:
# Shows the shape of the train and test feature set
print("Training feature shape: ", X_train.shape)
print("Testing feature shape: ", X_test.shape)

Training feature shape:  (1012, 57)
Testing feature shape:  (3589, 57)


In [10]:
# Showcasing the first 5 rows of training data
X_train.head()

make  address   all   3d   our  over  remove  internet  order  mail  \
440    0.0      0.0  0.00  0.0  0.00  0.80    0.00      0.00   0.80  0.00   
3507   0.4      0.4  0.26  0.0  0.13  0.20    0.06      0.33   0.00  1.14   
4423   0.0      0.0  0.00  0.0  0.00  0.23    0.00      0.00   0.00  0.23   
958    0.0      0.0  0.00  0.0  0.00  0.00    0.00      0.00   0.00  0.00   
2817   0.0      0.0  0.71  0.0  0.23  0.00    0.00      0.00   0.23  0.23   

      ...  conference  semicol  paren  bracket   bang  dollar  pound  cap_avg  \
440   ...        0.00      0.0  0.294      0.0  0.000   0.000   0.00    1.166   
3507  ...        0.00      0.0  0.088      0.0  1.060   0.151   0.05    4.623   
4423  ...        0.71      0.0  0.000      0.0  0.000   0.069   0.00    2.216   
958   ...        0.00      0.0  0.000      0.0  0.000   0.000   0.00    1.866   
2817  ...        0.00      0.0  0.109      0.0  1.018   0.036   0.00    4.022   

      cap_long  cap_total  
440          2         14  
3507       123       1045  
4423        44        215  
958          6         28  
2817        97        543  

[5 rows x 57 columns]

In [10]:
clf_dt = DecisionTreeClassifier(criterion = "entropy")
clf_lr = LogisticRegression()
clf_gnb = GaussianNB()
eclf = VotingClassifier(estimators = [('DT', clf_dt),('LR',clf_lr),('GNB',clf_gnb)], voting ='hard')

In [14]:
eclf.fit(X_train, y_train)
msg_test_target_predict = eclf.predict(X_test)
# Metrics performed on the test data
print("---------FUSED MODEL CLASSIFIER-------------")
print("CONFUSION MATRIX:\n", confusion_matrix(y_test, msg_test_target_predict))
print("TOTAL ACCURACY SCORE:{}%".format(round((accuracy_score(y_test, msg_test_target_predict))*100),2))
print("Accuracy of Ham class is {}%".format(round((recall_score(y_test, msg_test_target_predict,average='binary',pos_label=0))*100),2))
print("Accuracy of Spam class is {}%".format(round((recall_score(y_test, msg_test_target_predict,average='binary',pos_label=1))*100),2))

---------FUSED MODEL CLASSIFIER-------------
CONFUSION MATRIX:
 [[2007  153]
 [ 131 1298]]
TOTAL ACCURACY SCORE:92%
Accuracy of Ham class is 93%
Accuracy of Spam class is 91%


In [12]:
DT = DecisionTreeClassifier(criterion = "entropy")
ABclf = AdaBoostClassifier(n_estimators = 200,base_estimator = DT)

In [17]:
ABclf.fit(X_train, y_train)
msg_test_target_predict = ABclf.predict(X_test)
# Metrics performed on the test data
print("---------ADABOOST ENSEMBLE WITH DECISION TREE as a base learner-------------")
print("CONFUSION MATRIX:\n", confusion_matrix(y_test, msg_test_target_predict))
print("TOTAL ACCURACY SCORE:{}%".format(round((accuracy_score(y_test, msg_test_target_predict))*100),2))
print("Accuracy of Ham class is {}%".format(round((recall_score(y_test, msg_test_target_predict,average='binary',pos_label=0))*100),2))
print("Accuracy of Spam class is {}%".format(round((recall_score(y_test, msg_test_target_predict,average='binary',pos_label=1))*100),2))

---------ADABOOST ENSEMBLE WITH DECISION TREE as a base learner-------------
CONFUSION MATRIX:
 [[1951  209]
 [ 190 1239]]
TOTAL ACCURACY SCORE:89%
Accuracy of Ham class is 90%
Accuracy of Spam class is 87%


In [18]:
RFclf = RandomForestClassifier(n_estimators=1000)

In [19]:
RFclf.fit(X_train, y_train)
msg_test_target_predict = RFclf.predict(X_test)
# Metrics performed on the test data
print("---------RANDOM FOREST CLASSIFIER-------------")
print("CONFUSION MATRIX:\n", confusion_matrix(y_test, msg_test_target_predict))
print("TOTAL ACCURACY SCORE:{}%".format(round((accuracy_score(y_test, msg_test_target_predict))*100),2))
print("Accuracy of Ham class is {}%".format(round((recall_score(y_test, msg_test_target_predict,average='binary',pos_label=0))*100),2))
print("Accuracy of Spam class is {}%".format(round((recall_score(y_test, msg_test_target_predict,average='binary',pos_label=1))*100),2))

---------RANDOM FOREST CLASSIFIER-------------
CONFUSION MATRIX:
 [[2079   81]
 [ 158 1271]]
TOTAL ACCURACY SCORE:93%
Accuracy of Ham class is 96%
Accuracy of Spam class is 89%


<h3>Training - Testing split: 50% - 50%</h3>

In [8]:
# Splitting the train and test data using the Stratified kfold cross validation
X1_train,X1_test,y1_train,y1_test= train_test_split(x,y, test_size=0.50, stratify=y)

In [9]:
# Shows the shape of the train and test feature set
print("Training feature shape: ", X1_train.shape)
print("Testing feature shape: ", X1_test.shape)

Training feature shape:  (2300, 57)
Testing feature shape:  (2301, 57)


In [ ]:
# Using the Majority voting technique via the VotingClassifier model
clf_dt = DecisionTreeClassifier(criterion = "entropy")
clf_lr = LogisticRegression()
clf_gnb = GaussianNB()
eclf = VotingClassifier(estimators = [('DT', clf_dt),('LR',clf_lr),('GNB',clf_gnb)], voting ='hard')

In [11]:
eclf.fit(X1_train, y1_train)
msg_test_target_predict = eclf.predict(X1_test)
# Metrics performed on the test data
print("---------FUSED MODEL CLASSIFIER WITH 50%-50% SPLIT-------------")
print("CONFUSION MATRIX:\n", confusion_matrix(y1_test, msg_test_target_predict))
print("TOTAL ACCURACY SCORE:{}%".format(round((accuracy_score(y1_test, msg_test_target_predict))*100),2))
print("Accuracy of Ham class is {}%".format(round((recall_score(y1_test, msg_test_target_predict,average='binary',pos_label=0))*100),2))
print("Accuracy of Spam class is {}%".format(round((recall_score(y1_test, msg_test_target_predict,average='binary',pos_label=1))*100),2))

---------FUSED MODEL CLASSIFIER WITH 50%-50% SPLIT-------------
CONFUSION MATRIX:
 [[1290  104]
 [  62  845]]
TOTAL ACCURACY SCORE:93%
Accuracy of Ham class is 93%
Accuracy of Spam class is 93%


In [13]:
DT = DecisionTreeClassifier(criterion = "entropy")
ABclf = AdaBoostClassifier(n_estimators = 200,base_estimator = DT)

In [15]:
ABclf.fit(X1_train, y1_train)
msg_test_target_predict = ABclf.predict(X1_test)
# Metrics performed on the test data
print("---------ADABOOST ENSEMBLE WITH DECISION TREE as a base learner WITH 50%-50% SPLIT-------------")
print("CONFUSION MATRIX:\n", confusion_matrix(y1_test, msg_test_target_predict))
print("TOTAL ACCURACY SCORE:{}%".format(round((accuracy_score(y1_test, msg_test_target_predict))*100),2))
print("Accuracy of Ham class is {}%".format(round((recall_score(y1_test, msg_test_target_predict,average='binary',pos_label=0))*100),2))
print("Accuracy of Spam class is {}%".format(round((recall_score(y1_test, msg_test_target_predict,average='binary',pos_label=1))*100),2))

---------ADABOOST ENSEMBLE WITH DECISION TREE as a base learner WITH 50%-50% SPLIT-------------
CONFUSION MATRIX:
 [[1340   54]
 [  70  837]]
TOTAL ACCURACY SCORE:95%
Accuracy of Ham class is 96%
Accuracy of Spam class is 92%


<h3>Training - Testing split: 60% - 40%</h3>

In [20]:
# Splitting the train and test data using the Stratified kfold cross validation
X2_train,X2_test,y2_train,y2_test= train_test_split(x,y, test_size=0.40, stratify=y)

In [21]:
# Shows the shape of the train and test feature set
print("Training feature shape: ", X2_train.shape)
print("Testing feature shape: ", X2_test.shape)

Training feature shape:  (2760, 57)
Testing feature shape:  (1841, 57)


In [22]:
# Using the Majority voting technique via the VotingClassifier model
clf_dt = DecisionTreeClassifier(criterion = "entropy")
clf_lr = LogisticRegression()
clf_gnb = GaussianNB()
eclf = VotingClassifier(estimators = [('DT', clf_dt),('LR',clf_lr),('GNB',clf_gnb)], voting ='hard')

In [23]:
eclf.fit(X2_train, y2_train)
msg_test_target_predict = eclf.predict(X2_test)
# Metrics performed on the test data
print("---------FUSED MODEL CLASSIFIER WITH 60%-40% SPLIT-------------")
print("CONFUSION MATRIX:\n", confusion_matrix(y2_test, msg_test_target_predict))
print("TOTAL ACCURACY SCORE:{}%".format(round((accuracy_score(y2_test, msg_test_target_predict))*100),2))
print("Accuracy of Ham class is {}%".format(round((recall_score(y2_test, msg_test_target_predict,average='binary',pos_label=0))*100),2))
print("Accuracy of Spam class is {}%".format(round((recall_score(y2_test, msg_test_target_predict,average='binary',pos_label=1))*100),2))

---------FUSED MODEL CLASSIFIER WITH 60%-40% SPLIT-------------
CONFUSION MATRIX:
 [[1027   89]
 [  39  686]]
TOTAL ACCURACY SCORE:93%
Accuracy of Ham class is 92%
Accuracy of Spam class is 95%


In [24]:
DT = DecisionTreeClassifier(criterion = "entropy")
ABclf = AdaBoostClassifier(n_estimators = 200,base_estimator = DT)

In [25]:
ABclf.fit(X2_train, y2_train)
msg_test_target_predict = ABclf.predict(X2_test)
# Metrics performed on the test data
print("---------ADABOOST ENSEMBLE WITH DECISION TREE as a base learner WITH 60%-40% SPLIT-------------")
print("CONFUSION MATRIX:\n", confusion_matrix(y2_test, msg_test_target_predict))
print("TOTAL ACCURACY SCORE:{}%".format(round((accuracy_score(y2_test, msg_test_target_predict))*100),2))
print("Accuracy of Ham class is {}%".format(round((recall_score(y2_test, msg_test_target_predict,average='binary',pos_label=0))*100),2))
print("Accuracy of Spam class is {}%".format(round((recall_score(y2_test, msg_test_target_predict,average='binary',pos_label=1))*100),2))

---------ADABOOST ENSEMBLE WITH DECISION TREE as a base learner WITH 60%-40% SPLIT-------------
CONFUSION MATRIX:
 [[1074   42]
 [  58  667]]
TOTAL ACCURACY SCORE:95%
Accuracy of Ham class is 96%
Accuracy of Spam class is 92%


<h3>Training - Testing split: 70% - 30%</h3>

In [30]:
# Splitting the train and test data using the Stratified kfold cross validation
X3_train,X3_test,y3_train,y3_test= train_test_split(x,y, test_size=0.30, stratify=y)

In [31]:
# Shows the shape of the train and test feature set
print("Training feature shape: ", X3_train.shape)
print("Testing feature shape: ", X3_test.shape)

Training feature shape:  (3220, 57)
Testing feature shape:  (1381, 57)


In [32]:
# Using the Majority voting technique via the VotingClassifier model
clf_dt = DecisionTreeClassifier(criterion = "entropy")
clf_lr = LogisticRegression()
clf_gnb = GaussianNB()
eclf = VotingClassifier(estimators = [('DT', clf_dt),('LR',clf_lr),('GNB',clf_gnb)], voting ='hard')

In [33]:
eclf.fit(X3_train, y3_train)
msg_test_target_predict = eclf.predict(X3_test)
# Metrics performed on the test data
print("---------FUSED MODEL CLASSIFIER WITH 70%-30% SPLIT-------------")
print("CONFUSION MATRIX:\n", confusion_matrix(y3_test, msg_test_target_predict))
print("TOTAL ACCURACY SCORE:{}%".format(round((accuracy_score(y3_test, msg_test_target_predict))*100),2))
print("Accuracy of Ham class is {}%".format(round((recall_score(y3_test, msg_test_target_predict,average='binary',pos_label=0))*100),2))
print("Accuracy of Spam class is {}%".format(round((recall_score(y3_test, msg_test_target_predict,average='binary',pos_label=1))*100),2))

---------FUSED MODEL CLASSIFIER WITH 70%-30% SPLIT-------------
CONFUSION MATRIX:
 [[778  59]
 [ 41 503]]
TOTAL ACCURACY SCORE:93%
Accuracy of Ham class is 93%
Accuracy of Spam class is 92%


In [34]:
DT = DecisionTreeClassifier(criterion = "entropy")
ABclf = AdaBoostClassifier(n_estimators = 200,base_estimator = DT)

In [35]:
ABclf.fit(X3_train, y3_train)
msg_test_target_predict = ABclf.predict(X3_test)
# Metrics performed on the test data
print("---------ADABOOST ENSEMBLE WITH DECISION TREE as a base learner WITH 70%-30% SPLIT-------------")
print("CONFUSION MATRIX:\n", confusion_matrix(y3_test, msg_test_target_predict))
print("TOTAL ACCURACY SCORE:{}%".format(round((accuracy_score(y3_test, msg_test_target_predict))*100),2))
print("Accuracy of Ham class is {}%".format(round((recall_score(y3_test, msg_test_target_predict,average='binary',pos_label=0))*100),2))
print("Accuracy of Spam class is {}%".format(round((recall_score(y3_test, msg_test_target_predict,average='binary',pos_label=1))*100),2))

---------ADABOOST ENSEMBLE WITH DECISION TREE as a base learner WITH 70%-30% SPLIT-------------
CONFUSION MATRIX:
 [[799  38]
 [ 46 498]]
TOTAL ACCURACY SCORE:94%
Accuracy of Ham class is 95%
Accuracy of Spam class is 92%


<h3>Training - Testing split: 80% - 20%</h3>

In [40]:
# Splitting the train and test data using the Stratified kfold cross validation
X4_train,X4_test,y4_train,y4_test= train_test_split(x,y, test_size=0.20, stratify=y)

In [41]:
# Shows the shape of the train and test feature set
print("Training feature shape: ", X4_train.shape)
print("Testing feature shape: ", X4_test.shape)

Training feature shape:  (3680, 57)
Testing feature shape:  (921, 57)


In [42]:
# Using the Majority voting technique via the VotingClassifier model in Ensemble Learning
clf_dt = DecisionTreeClassifier(criterion = "entropy")
clf_lr = LogisticRegression()
clf_gnb = GaussianNB()
eclf = VotingClassifier(estimators = [('DT', clf_dt),('LR',clf_lr),('GNB',clf_gnb)], voting ='hard')

In [43]:
eclf.fit(X4_train, y4_train)
msg_test_target_predict = eclf.predict(X4_test)
# Metrics performed on the test data
print("---------FUSED MODEL CLASSIFIER WITH 80%-20% SPLIT-------------")
print("CONFUSION MATRIX:\n", confusion_matrix(y4_test, msg_test_target_predict))
print("TOTAL ACCURACY SCORE:{}%".format(round((accuracy_score(y4_test, msg_test_target_predict))*100),2))
print("Accuracy of Ham class is {}%".format(round((recall_score(y4_test, msg_test_target_predict,average='binary',pos_label=0))*100),2))
print("Accuracy of Spam class is {}%".format(round((recall_score(y4_test, msg_test_target_predict,average='binary',pos_label=1))*100),2))

---------FUSED MODEL CLASSIFIER WITH 80%-20% SPLIT-------------
CONFUSION MATRIX:
 [[525  33]
 [ 22 341]]
TOTAL ACCURACY SCORE:94%
Accuracy of Ham class is 94%
Accuracy of Spam class is 94%


In [44]:
DT = DecisionTreeClassifier(criterion = "entropy")
ABclf = AdaBoostClassifier(n_estimators = 200,base_estimator = DT)

In [45]:
ABclf.fit(X4_train, y4_train)
msg_test_target_predict = ABclf.predict(X4_test)
# Metrics performed on the test data
print("---------ADABOOST ENSEMBLE WITH DECISION TREE as a base learner WITH 80%-20% SPLIT-------------")
print("CONFUSION MATRIX:\n", confusion_matrix(y4_test, msg_test_target_predict))
print("TOTAL ACCURACY SCORE:{}%".format(round((accuracy_score(y4_test, msg_test_target_predict))*100),2))
print("Accuracy of Ham class is {}%".format(round((recall_score(y4_test, msg_test_target_predict,average='binary',pos_label=0))*100),2))
print("Accuracy of Spam class is {}%".format(round((recall_score(y4_test, msg_test_target_predict,average='binary',pos_label=1))*100),2))

---------ADABOOST ENSEMBLE WITH DECISION TREE as a base learner WITH 80%-20% SPLIT-------------
CONFUSION MATRIX:
 [[543  15]
 [ 26 337]]
TOTAL ACCURACY SCORE:96%
Accuracy of Ham class is 97%
Accuracy of Spam class is 93%
